name         'smarchive-rundeck'
version      '0.1.0'
author       'Jochen Schalanda'
license      'Apache 2.0'
project_page 'https://github.com/smarchive/puppet-rundeck'
source       'https://github.com/smarchive/puppet-rundeck'
summary      'Puppet module for managing Rundeck'
description  'This module installs and manages Rundeck, an open-source process automation and command orchestration tool. Check README.md for details.'
dependency   'puppetlabs/stdlib', '>= 2.0.0'
