name         'gini-rundeck'
version      '0.2.0'
author       'Jochen Schalanda'
license      'Apache 2.0'
project_page 'https://github.com/gini/puppet-rundeck'
source       'https://github.com/gini/puppet-rundeck'
summary      'Puppet module for managing Rundeck'
description  'This module installs and manages Rundeck, an open-source process automation and command orchestration tool. Please check README.md for details.'
dependency   'puppetlabs/stdlib', '3.x'
